# =============================================================================
# sPLS-DA tuning for factor "{{FACTOR}}" — generated by ExploreMetabar.
#
# Tuning is slow (cross-validation over many components and keepX values), so
# ExploreMetabar hands it off to you to run in your own R session. Once it has
# finished, type the suggested ncomp / keepX into panel 1 (Run sPLS-DA) of the
# app to obtain the final model.
#
# Requirements: the mixOmics package, and the file "splsda_input.rds" that came
# in the same zip (it holds the exact X / Y the app would have used).
# =============================================================================

library(mixOmics)
# library(BiocParallel)   # optional: parallelize the tuning (see BPPARAM below)

# Set the working directory to the folder where you unzipped the kit, or pass a
# full path to readRDS() below.
dat <- readRDS("splsda_input.rds")
X <- dat$X        # samples x taxa abundance matrix
Y <- dat$Y        # factor "{{FACTOR}}", one level per sample
set.seed(1)       # reproducibility — change or remove as you wish

## 1. Choose the number of components with perf() -----------------------------
# Fit a full model, then evaluate classification error across components by
# repeated M-fold cross-validation. Inspect the plot: keep the smallest ncomp
# beyond which the error stops improving.
init <- splsda(X, Y, ncomp = 10)
perf.res <- perf(init, validation = "Mfold", folds = 10,
                 nrepeat = 10, auc = TRUE, progressBar = TRUE)
plot(perf.res, sd = TRUE, legend.position = "horizontal")

# Automatic suggestion for the chosen distance / measure:
ncomp <- perf.res$choice.ncomp["{{MEASURE}}", "{{DISTANCE}}"]
ncomp <- ifelse(ncomp == 1, 2, ncomp)   # need at least 2 components to plot

## 2. Choose the number of features per component with tune.splsda() ----------
# For each component, cross-validate over a grid of keepX (number of features
# kept) and pick the value minimising the error. This is the slow step.
test.keepX <- c(1:10, seq(20, 300, 10))
tune.res <- tune.splsda(X, Y, ncomp = ncomp,
                        validation = "Mfold", folds = 5, nrepeat = 10,
                        dist = "{{DISTANCE}}", measure = "{{MEASURE}}",
                        test.keepX = test.keepX,
                        progressBar = TRUE)
                        # , BPPARAM = BiocParallel::MulticoreParam(workers = 4))
plot(tune.res)

## 3. Read off the values to enter back into the app -------------------------
final.ncomp <- tune.res$choice.ncomp$ncomp
final.keepX <- as.integer(tune.res$choice.keepX[seq_len(final.ncomp)])
cat("\n==================================================\n",
    "Enter these in panel 1 (Run sPLS-DA) of the app:\n",
    "  Number of components :", final.ncomp, "\n",
    "  keepX per component  :", paste(final.keepX, collapse = ", "), "\n",
    "==================================================\n")
